/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class MainPrj extends javax.swing.JFrame {

    String args[];
    /**
     * Creates new form MainPrj
     */
    public MainPrj() {
        initComponents();
    }
    
    
    public MainPrj(String args[])
    {
        
        this.args = args;
        initComponents();
        updateInput.setVisible(false);
        update.setVisible(false);
        //JOptionPane.showMessageDialog(null, "\n\n\t" + args[0]  );
            
          try {  
            boolean flag;
            // TODO add your handling code here:
            String path = "jdbc:mysql://localhost:3306/emp";
            Connection con =  DriverManager.getConnection(path,"root","root");
            Statement st = con.createStatement();
            String Query = "select * from emp.employee where name = '" + args[0] + "'";
            ResultSet rs = st.executeQuery(Query);
            flag = rs.next();
            String s;
            if(flag)
            {
                Object o = rs.getString("prj_nm");
                if( o == null)
                {
                    
                    lblPrjName.setVisible(false);
                    lblPrjDetail.setVisible(false);
                    lblPrjDeadline.setVisible(false);
                    lblPrjProgress.setVisible(false);
                    prjName.setVisible(false);
                    prjDetail.setVisible(false);
                    prjDeadline.setVisible(false);
                    prjProgress.setVisible(false);
                    btnUpdate.setVisible(false);
                    lblMsg.setText("You have no Projects Now !");
                }
                else
                {
                    boolean flag2 = false;
            // TODO add your handling code here:
                    String path2 = "jdbc:mysql://localhost:3306/emp";
                    Connection con2 =  DriverManager.getConnection(path2,"root","root");
                    Statement st2 = con2.createStatement();
                    String Query2 = "select * from emp.project where prj_name = '" + rs.getString("prj_nm") + "'";
                    ResultSet rs2 = st2.executeQuery(Query2);
                    flag2 = rs2.next();
                    
                    
                    
                    if(flag2)
                    {
                        s = rs2.getString("prj_name");
                        lblPrjName.setText(s);
                        s = rs2.getString("prj_detail");
                        lblPrjDetail.setText(s);
                        s = rs2.getString("deadline");
                        lblPrjDeadline.setText(s);
                        s = rs2.getString("progress");
                        lblPrjProgress.setText(s + " %");
                
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null, " Error : No Data Found !"  );
                    }
                }
                
                
                
            }
            else
            {
                JOptionPane.showMessageDialog(null, " Error : No Data Found !"  );
            }
            }
          catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnProfile = new javax.swing.JButton();
        btnPrj = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblMsg = new javax.swing.JLabel();
        prjName = new javax.swing.JLabel();
        lblPrjName = new javax.swing.JLabel();
        prjDetail = new javax.swing.JLabel();
        lblPrjDetail = new javax.swing.JLabel();
        prjDeadline = new javax.swing.JLabel();
        lblPrjDeadline = new javax.swing.JLabel();
        prjProgress = new javax.swing.JLabel();
        lblPrjProgress = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        updateInput = new javax.swing.JTextField();
        update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnPrj.setText("Projects");
        btnPrj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrjActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblMsg.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        lblMsg.setForeground(new java.awt.Color(255, 255, 255));
        lblMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMsg.setText("Welcome to the Projects ");

        prjName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        prjName.setForeground(new java.awt.Color(255, 255, 255));
        prjName.setText("Project Name      :");

        lblPrjName.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblPrjName.setForeground(new java.awt.Color(255, 255, 255));

        prjDetail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        prjDetail.setForeground(new java.awt.Color(255, 255, 255));
        prjDetail.setText("Project Detail      :");

        lblPrjDetail.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblPrjDetail.setForeground(new java.awt.Color(255, 255, 255));

        prjDeadline.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        prjDeadline.setForeground(new java.awt.Color(255, 255, 255));
        prjDeadline.setText("Project Deadline :");

        lblPrjDeadline.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblPrjDeadline.setForeground(new java.awt.Color(255, 255, 255));

        prjProgress.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        prjProgress.setForeground(new java.awt.Color(255, 255, 255));
        prjProgress.setText("Progress             :");

        lblPrjProgress.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblPrjProgress.setForeground(new java.awt.Color(255, 255, 255));

        btnUpdate.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnUpdate.setText("Update Progress ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        updateInput.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        updateInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInputActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(btnProfile, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnPrj, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnLogout, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblMsg, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(prjName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblPrjName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(prjDetail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblPrjDetail, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(prjDeadline, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblPrjDeadline, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(prjProgress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lblPrjProgress, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(updateInput, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(update, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnPrj, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(prjDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblPrjDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(prjDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblPrjDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(prjName, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(lblPrjName, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prjProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrjProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(updateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrj, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prjName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrjName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prjDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrjDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prjDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrjDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prjProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrjProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateInput)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        Main.main(args);
        this.dispose();

    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        String args[] = {""};
        ask.main(args);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void updateInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateInputActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        boolean flag = update.isVisible();
        update.setVisible(!flag);
        updateInput.setVisible(!flag);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if(updateInput.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Invalid Input"  );
        }
        else
        {
            float i=0;
            boolean f;
            try{
                i = Float.parseFloat(updateInput.getText());
                f = true;
            }
            catch(Exception e)
            {
                f = false;
            }
            if(f)
            {
                try {
                    String path = "jdbc:mysql://localhost:3306/emp";
                    Connection con =  DriverManager.getConnection(path,"root","root");
                    Statement st = con.createStatement();
                    String Query = "update emp.project set progress = " + i + " where prj_name = '" + lblPrjName.getText()  + "'";
                    st.executeUpdate(Query);
                    MainPrj.main(this.args);
                    this.dispose();
                    
                } catch (SQLException ex) {
                    Logger.getLogger(MainPrj.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Progress must be Numeric !"  );
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void btnPrjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrjActionPerformed
        // TODO add your handling code here:
        MainPrj.main(args);
        this.dispose();
    }//GEN-LAST:event_btnPrjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPrj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPrj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPrj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPrj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPrj(args).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrj;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblPrjDeadline;
    private javax.swing.JLabel lblPrjDetail;
    private javax.swing.JLabel lblPrjName;
    private javax.swing.JLabel lblPrjProgress;
    private javax.swing.JLabel prjDeadline;
    private javax.swing.JLabel prjDetail;
    private javax.swing.JLabel prjName;
    private javax.swing.JLabel prjProgress;
    private javax.swing.JButton update;
    private javax.swing.JTextField updateInput;
    // End of variables declaration//GEN-END:variables
}
